import { Metadata } from 'next'
import VacanciesPage from '../../components/VacanciesPage'

export const metadata: Metadata = {
  title: 'JDG | Vagas',
  description: 'Generated by create next app',
}

export default function Vacancies() {
  return <VacanciesPage />
}
