import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Container from './components/Container'
import Header from './components/Header'
import Footer from './components/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '400', '600', '700'],
})

export const metadata: Metadata = {
  title: 'JDG | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  )
}
